// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPOqWQkIv9DDvz7HLTzizwn1_L9i-oWXc',
    appId: '1:5551288253:web:50b453cec74147c447ecd4',
    messagingSenderId: '5551288253',
    projectId: 'owen-wilson-app',
    authDomain: 'owen-wilson-app.firebaseapp.com',
    storageBucket: 'owen-wilson-app.appspot.com',
    measurementId: 'G-0690LHR2JC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1HMKBO2wdekacsZimEJBHXBO46QRrTcQ',
    appId: '1:5551288253:android:b10aa0b2c96caa2e47ecd4',
    messagingSenderId: '5551288253',
    projectId: 'owen-wilson-app',
    storageBucket: 'owen-wilson-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDa-5Jmi_IUzJwNyXUJfkOC302VKXaK3Fw',
    appId: '1:5551288253:ios:a2eb4c9cf019b35447ecd4',
    messagingSenderId: '5551288253',
    projectId: 'owen-wilson-app',
    storageBucket: 'owen-wilson-app.appspot.com',
    iosClientId: '5551288253-upbdiei17b02u0tukq8upcl0h96qhkpo.apps.googleusercontent.com',
    iosBundleId: 'com.example.owenWilson',
  );
}
